### ISSUE TITLE
Join efforts?

### ISSUE THREAD

**Issue by aaronjanse** [emmettgb/BashRepl.jl#5]
Hey, this is an awesome project!

I've been building something similar ([REPLComboShell.jl](https://github.com/aaronjanse/REPLComboShell.jl)), which uses `fish` for fuzzy autocomplete while still allowing autocomplete from Julia. I've also figured out ctrl-c and having the combo repl be used as the default.

Would you be interested in somehow working together on a julia shell?

**Comment by emmaccode** [comment]
Hmmm sure, sounds cool. This was mostly me just playing around a bit with REPLMaker (; makes the whole thing obsolete," but I'm sure a fork can generate some contributions of some type.
